import numpy as np
from scipy.optimize import fsolve
from cooling_analysis import analyze_cooling_system
from config import T_in, M_DOT
from heptane_itpl import calculate_h, Cp_func, rho_func

class SystemParams:
    def __init__(self):
        # Geometry parameters from the paper
        self.n = 5  # number of branches
        self.D = 17e-03  # main pipe diameter (m)
        self.w_branch = 30e-03  # branch width (m)
        self.h_branch = 2.75e-03  # branch height (m)
        self.L_a = 0.5  # main pipe length per segment (m)
        self.L_b = 0.5  # branch length (m)
        self.g = 9.81  # gravitational acceleration (m/s²)
        
        # Calculate areas
        self.S_a = np.pi * (self.D/2)**2  # main pipe cross-sectional area
        self.S_b = self.w_branch * self.h_branch  # branch cross-sectional area
        self.d_H = 2 * self.w_branch * self.h_branch / (self.w_branch + self.h_branch)  # hydraulic diameter

# HYDRAULIC BALANCE FUNCTIONS

def pump_head_curve(mass_flow_rate_kg_s):
    # could be replaced with real pump curve if available
    # for now, assume constant pressure head supplied
    P_fixed_supplied = 5000.0  # Constant pressure head supplied to the single channel (Pa)
    return P_fixed_supplied

# root finding of coupled system
def pressure_balance_couple(mass_flow_rate_kg_s, params):
    """
    Function whose root represents the hydraulic balance (P_pump - P_loss = 0).
    """
    m_dot = mass_flow_rate_kg_s
    if m_dot <= 1e-9: return 1e10 # High residual for non-physical flow
    
    # 1. Thermal Balance (to find T_c_avg)
    # Use Cp at inlet temperature for bulk energy calculation (simplification)
    Cp_c_in = Cp_func(params.T_c_in)
    # calculate outlet temp with energy balance
    T_c_out_K = params.T_c_in + params.I_sq_R / (m_dot * Cp_c_in)
    # average Coolant Temperature
    T_c_avg_K = (params.T_c_in + T_c_out_K) / 2
    
    # 2. Hydraulic Balance
    V_dot = m_dot / rho_func(T_c_avg_K)  # m³/s
    # calculate the head loss in the system
    results = analyze_cooling_system(V_dot * 1000 * 60)  # Convert to L/min 
    # Extract total head loss for Group A
    head_loss = results['head_loss_analysis']['total_group_A_head_loss_m']
    P_loss_system = head_loss * rho_func(T_c_avg_K) * params.g  # Pa
    # calculate supplied head
    P_supplied_pump = pump_head_curve(m_dot)
    
    # 4. Return the residual head
    return P_supplied_pump - P_loss_system


def calculate_steady_state_mass_flow(Q_gen, T_c_in, guess_m_dot):
    """
    Finds the steady-state mass flow rate (m_dot_ss) and calculates
    the resulting thermal properties (h, Tc_avg).
    """
    params = SystemParams()
    params.I_sq_R = Q_gen
    params.T_c_in = T_c_in
    
    # 1. Solve for m_dot_ss
    # fsolve returns an array for m_dot_ss
    m_dot_ss, info, ier, msg = fsolve(
        pressure_balance_couple, 
        guess_m_dot, 
        args=(params,), 
        full_output=True,
        xtol=1e-6 
    )
    
    m_dot = m_dot_ss[0]

    # 2. Calculate resulting thermal parameters at steady state
    Cp_c_in = Cp_func(params.T_c_in)
    T_c_out_K = params.T_c_in + params.I_sq_R / (m_dot * Cp_c_in)
    T_c_avg_K = (params.T_c_in + T_c_out_K) / 2
    
    # Calculate h using the real imported function
    # Note: The real calculate_h signature is (T, m_dot, D)
    h_ss = calculate_h(T_c_avg_K, m_dot, params.D_pipe)
    
    return m_dot, T_c_avg_K, h_ss




#AI FOR TESTING ONLY
if __name__ == '__main__':
    # Define inputs for this single cell scenario
    # *** USER MUST UPDATE THESE VALUES ***
    Q_gen = 30**2 *0.6        # Watts (I^2*R) - Heat generated by this single cell
    T_c_in_K = T_in    # Kelvin (20.0 °C)
    m_dot_guess = M_DOT  # Initial guess for the solver (e.g., 5 g/s)

    # Note: SystemParams must be instantiated here for reporting the constants
    params = SystemParams()
    # Update execution parameters from the class
    Q_gen = params.I_sq_R
    T_c_in_K = params.T_c_in

    # *** FIX: Updated to match the function's 3 return values ***
    m_dot_ss_kg_s, T_c_avg_K, h_ss = calculate_steady_state_mass_flow(
        Q_gen, T_c_in_K, m_dot_guess
    )

    print("\n" + "="*50)
    print("      SINGLE-CELL STEADY-STATE FLOW & THERMAL SOLVER")
    print("="*50)
    print(f"Cell Heat Generation (Q_gen): {Q_gen} W")
    print(f"Coolant Inlet Temperature (T_c,in): {T_c_in_K:.2f} K")
    print("-----------------------------------------")
    
    # Simplified check: if m_dot is positive, solver was successful.
    if m_dot_ss_kg_s > 0:
        print("✅ Steady-State Operating Point Found")
        print("-----------------------------------------")
        print(f"Empirical Mass Flow Rate (m_dot_ss): {m_dot_ss_kg_s:.5f} kg/s")
        print(f"Average Coolant Temperature (T_c,avg): {T_c_avg_K:.2f} K ({T_c_avg_K - 273.15:.2f} °C)")
        print(f"Heat Transfer Coefficient (h): {h_ss:.2f} W/(m²·K)")
        # T_b_ss and status reporting removed as they are no longer calculated/returned.
        
        # Calculate the pressure values for comparison
        P_pump_ss = pump_head_curve(m_dot_ss_kg_s)
        P_system_ss = system_head_loss_calc(m_dot_ss_kg_s, T_c_avg_K, 
                                            params.D_pipe, params.L_pipe, 
                                            params.K_minor, params.epsilon)
        print("\nHydraulic Balance Check:")
        print(f"Supplied Pressure Drop (dP_pump): {P_pump_ss:.2f} Pa (Fixed)")
        print(f"Channel Head Loss (dP_system): {P_system_ss:.2f} Pa")
        print(f"Residual (dP_pump - dP_system): {P_pump_ss - P_system_ss:.2e} Pa")
        
    else:
        # Note: 'status' is no longer available, so print a general failure message.
        print("❌ Calculation failed. Solver did not converge or found non-physical flow.")
