import numpy as np
from scipy.optimize import fsolve
import sympy as sp
from pathlib import Path
from heptane_itpl_mdottest import (
        calculate_h, 
        Cp_func, 
        rho_func, 
        mu_func,
        lambda_func # lambda_func (thermal conductivity) is also needed by calculate_h
    )

class SystemParams:
    # we need to decide these values (maybe from geometry optimization?)
    I_sq_R = 10.0           # Steady-state generated heat, I^2 * R (Watts) - Heat from THIS cell
    T_c_in = 293.15         # Coolant inlet temperature (K) - Inlet T to THIS channel
    
    # --- Geometry & Fluid Inputs (Single Channel Path) ---
    N = 6 # number of internal structures in branch
    w_branch = 30e-03/(N+1) # equivalent internal width of branch (m)
    h_branch = 2.75e-03    # equivalent internal height of branch (m)
    d_H = 2 * w_branch * h_branch/ (w_branch + h_branch)       # Hydraulic Diameter of branch (m)
    D = 17e-03    # main pipe diameter (m)
    S_a = np.pi * (D/2)**2  # main pipe cross-sectional area (m^2)
    S_b = w_branch * h_branch # branch cross-sectional area (m^2)
    L_a = 0.5    # main pipe length (m)
    L_b = 0.5      # Branch length (m)
    n = 5        # number of branches
    g = 9.81     # gravitational acceleration (m/s^2)

# HYDRAULIC BALANCE FUNCTIONS

def pump_head_curve(mass_flow_rate_kg_s):
    # could be replaced with real pump curve if available
    # for now, assume constant pressure head supplied
    P_fixed_supplied = 5000.0  # Constant pressure head supplied to the single channel (Pa)
    return P_fixed_supplied

def H_i(T_c_avg_K, n):
    
    rho = rho_func(T_c_avg_K)
    mu = mu_func(T_c_avg_K)
    nu = mu / rho  # kinematic viscosity    

    Q = sp.symbols(f'Q1:{n+1}')
    H = sp.symbols(f'H1:{n+1}')
    
    equations = []
    
    # Define the constant term for the La part
    for i in range(1, n + 1):
        # Inner sum over all Q_m / Sa
        inner_sum = sum(Q[m] / SystemParams.Sa for m in range(n))
        
        # Outer sum: both terms inside
        outer_sum = 0
        for k in range(1, i + 1):
            term_a = (32 * nu * SystemParams.La / (SystemParams.d**2 * g)) * inner_sum
            term_b = (32 * nu * SystemParams.Lb * Q[k-1]) / (SystemParams.d_H**2 * SystemParams.g * SystemParams.Sb)
            outer_sum += term_a + term_b
        
        H_expr = 2 * outer_sum
        equations.append(sp.Eq(H[i-1], H_expr))
    
    return equations, H, Q

print(H_i(300, 3))  # Example usage
# root finding of coupled system
def pressure_balance_couple(mass_flow_rate_kg_s, params):
    """
    Function whose root represents the hydraulic balance (P_pump - P_loss = 0).
    """
    m_dot = mass_flow_rate_kg_s
    if m_dot <= 1e-9: return 1e10 # High residual for non-physical flow
    
    # 1. Thermal Balance (to find T_c_avg)
    # Use Cp at inlet temperature for bulk energy calculation (simplification)
    Cp_c_in = Cp_func(params.T_c_in)
    # calculate outlet temp with energy balance
    T_c_out_K = params.T_c_in + params.I_sq_R / (m_dot * Cp_c_in)
    # average Coolant Temperature
    T_c_avg_K = (params.T_c_in + T_c_out_K) / 2
    
    # 2. Hydraulic Balance
    # calculate the head loss in the system
    P_loss_system = system_head_loss_calc(
        m_dot, T_c_avg_K, params.D_pipe, 
        params.L_pipe, params.K_minor, params.epsilon
    )
    # calculate supplied head
    P_supplied_pump = pump_head_curve(m_dot)
    
    # 4. Return the residual head
    return P_supplied_pump - P_loss_system


def calculate_steady_state_mass_flow(Q_gen, T_c_in, guess_m_dot):
    """
    Finds the steady-state mass flow rate (m_dot_ss) and calculates
    the resulting thermal properties (h, Tc_avg).
    """
    params = SystemParams()
    params.I_sq_R = Q_gen
    params.T_c_in = T_c_in
    
    # 1. Solve for m_dot_ss
    # fsolve returns an array for m_dot_ss
    m_dot_ss, info, ier, msg = fsolve(
        pressure_balance_couple, 
        guess_m_dot, 
        args=(params,), 
        full_output=True,
        xtol=1e-6 
    )
    
    m_dot = m_dot_ss[0]

    # 2. Calculate resulting thermal parameters at steady state
    Cp_c_in = Cp_func(params.T_c_in)
    T_c_out_K = params.T_c_in + params.I_sq_R / (m_dot * Cp_c_in)
    T_c_avg_K = (params.T_c_in + T_c_out_K) / 2
    
    # Calculate h using the real imported function
    # Note: The real calculate_h signature is (T, m_dot, D)
    h_ss = calculate_h(T_c_avg_K, m_dot, params.D_pipe)
    
    return m_dot, T_c_avg_K, h_ss






#AI FOR TESTING ONLY
if __name__ == '__main__':
    # Define inputs for this single cell scenario
    # *** USER MUST UPDATE THESE VALUES ***
    Q_gen = 10.0         # Watts (I^2*R) - Heat generated by this single cell
    T_c_in_K = 293.15    # Kelvin (20.0 °C)
    m_dot_guess = 0.005  # Initial guess for the solver (e.g., 5 g/s)

    # Note: SystemParams must be instantiated here for reporting the constants
    params = SystemParams()
    # Update execution parameters from the class
    Q_gen = params.I_sq_R
    T_c_in_K = params.T_c_in

    # *** FIX: Updated to match the function's 3 return values ***
    m_dot_ss_kg_s, T_c_avg_K, h_ss = calculate_steady_state_mass_flow(
        Q_gen, T_c_in_K, m_dot_guess
    )

    print("\n" + "="*50)
    print("      SINGLE-CELL STEADY-STATE FLOW & THERMAL SOLVER")
    print("="*50)
    print(f"Cell Heat Generation (Q_gen): {Q_gen} W")
    print(f"Coolant Inlet Temperature (T_c,in): {T_c_in_K:.2f} K")
    print("-----------------------------------------")
    
    # Simplified check: if m_dot is positive, solver was successful.
    if m_dot_ss_kg_s > 0:
        print("✅ Steady-State Operating Point Found")
        print("-----------------------------------------")
        print(f"Empirical Mass Flow Rate (m_dot_ss): {m_dot_ss_kg_s:.5f} kg/s")
        print(f"Average Coolant Temperature (T_c,avg): {T_c_avg_K:.2f} K ({T_c_avg_K - 273.15:.2f} °C)")
        print(f"Heat Transfer Coefficient (h): {h_ss:.2f} W/(m²·K)")
        # T_b_ss and status reporting removed as they are no longer calculated/returned.
        
        # Calculate the pressure values for comparison
        P_pump_ss = pump_head_curve(m_dot_ss_kg_s)
        P_system_ss = system_head_loss_calc(m_dot_ss_kg_s, T_c_avg_K, 
                                            params.D_pipe, params.L_pipe, 
                                            params.K_minor, params.epsilon)
        print("\nHydraulic Balance Check:")
        print(f"Supplied Pressure Drop (dP_pump): {P_pump_ss:.2f} Pa (Fixed)")
        print(f"Channel Head Loss (dP_system): {P_system_ss:.2f} Pa")
        print(f"Residual (dP_pump - dP_system): {P_pump_ss - P_system_ss:.2e} Pa")
        
    else:
        # Note: 'status' is no longer available, so print a general failure message.
        print("❌ Calculation failed. Solver did not converge or found non-physical flow.")
